/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/images/dark_astronaut.glb 
Author: Charles Cloutier (https://sketchfab.com/Allastar)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dark-astronaut-1b2d325edc814d068e920add2ecc8a32
Title: Dark Astronaut
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/dark_astronaut.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes._rootJoint} />
      <skinnedMesh geometry={nodes.Object_6.geometry} material={materials.Armure} skeleton={nodes.Object_6.skeleton} />
      <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.Corps} skeleton={nodes.Object_7.skeleton} />
    </group>
  )
}

useGLTF.preload('/dark_astronaut.glb')
